# -*- coding: utf-8 -*-
"""Hola mundo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iw1Y4nrQLdoMKFKAG8ltiCY7EzQROQjL
"""

print("Hola mundo")